sudo: false
language: node_js
node_js: stable
env:
  global:
    secure: hIHZ5P48DWOutf1bVvcEzgYw34kqPOwgmJoMzY0eJJGCDnvGr238SDaeeOcGJ0Qy0M4H1J21j5ig9oEpAJIRW7GKuLxBebbb9nSPaFFzLeS33kRgg1jr7cZUi55LBk9wu6DINazry3gjNgc1dpEIt9tUIHTnWdFPIKXVruGMSP0ojJRmbaUQQRLf2kTof+VN6MM/5zSSiwZBACTnMjkmz2/fWybHoE9NnMAmdrGSEmFqOvCMU1LM7DYGB+3sD3m8rUwIESFxhVBQBye5R9hPSKOFks/YCAXOvQcPL7sanQvceCMmqNbKhUNNFJkZC9tvus3xbgSlhsyF5B8pJbTEMTB5U7pgSYntF6RrqznRbyjUaGA9lwOE3OstGcXkDDkzyl1hlg9ykyW1kd9tE+J7IEhFkNDqi94bfD8wMaW8dwCCor9mbY4lodL7txefJOH5DpUbHNKlX2azdtYFifP7CYfiwbQ73ciAKjWWlvgTDiPKxRIr2wC/zb19IVxxmvwuhLclCQz4mCyDxfy/jxLYmB/KDui3Ruf7I0fMsZMKlriEHf2p7azDgx7QGWYIn0zVRhoK/5nxRwgQY80ImtjOS5sc8jHn7EJRN1GG0ZgbrVn69UbT1jaaJF6MHsJjlkMkCKY5PnpbIcOHM62e3GXAx8NnLvv2pVhdt7z/buZ6K3s=
